### ISSUE TITLE
user story1

### ISSUE THREAD

**Issue by Mariana-x1** [Mariana-x1/capstone-project#1]
## Value proposition

- As a user
- I want to see a list of different coffee varieties
- So that I get inspired which coffee I want to try next.

## Description

![Image](https://github.com/Mariana-x1/capstone-project/assets/136748039/e51b20b9-475a-4edf-8428-8973ede96cad)

## Acceptance criteria

- [ ] A list of different coffee varieties is displayed.
- [ ] For each coffee variety there is an image and
name displayed.    name: Espresso.   text: Hausmischung.

- [ ] The list scrolls vertically
- [ ] All list items have the same height.

## Tasks

- [ ]  create a branch feat/GalleryCafe-list
- [ ]  create a new page index.js 
- [ ]  Add component: GalleryCafe-List.
- [ ]  Add a lib folder: db.js with array. 
- [ ]  {
"id": "123"
"image": "url", 
"name": "Espresso",
"text": "Hausmischung",
}

- [ ]  write function with map Array
- [ ]  return in index.js

**Comment by ninaassmann** [comment]
i guess you don't need the index in the object, but the rest LGTM

**Comment by Mariana-x1** [comment]
danke Nina 
LGTM

**Comment by F-Kirchhoff** [comment]
looks good to me (LGTM)
