### ISSUE TITLE
user story2

### ISSUE THREAD

**Issue by Mariana-x1** [Mariana-x1/capstone-project#2]
## Value proposition

As an user
I want to click on the image and the user is redirected to the details page.
So that I can get even more infos about coffee

## Description

![detailansicht1](https://github.com/Mariana-x1/capstone-project/assets/136748039/268c535b-69fb-49df-9a5b-cb9a392d4e6a)

## Acceptance criteria

- [ ] A image of a coffee is displayed.
- [ ] For this coffee variety there is one image,
        name and same sentence about coffee. 
- [ ] when the picture is clicked the user hovers the image, it is enlarged

## Tasks

- [ ]  create a branch " feat/details-CoffeeList and add link" 
- [ ] create a link for the image in the CoffeeLink component: to see more details.
- [ ] Create styling for all coffee-Card in the list and this will be displayed later,

**Comment by F-Kirchhoff** [comment]
Here are the things I would suggest to improve this US:
- you don't need to mention the back button in the value proposition (thats too much detail)
- specify the behavior that should be added with this user story (if the image is clicked, the user is redirected to the details page)
- you don't need to specify the specific text that should be displayed (it should be different for each coffee anyways)
- you don't need the event handler on the image, since you want the user to be redirected to a separate page in your next.js application (you can use the `Link` component from next.js for that, have a look at the handout `next.js basics and routing`

Hope that helped!

**Comment by F-Kirchhoff** [comment]
Hey Marie,
please add some more detail about the tasks. Also, add an acceptance criteria for the clicking behavior. After that you are good to go!

**Comment by F-Kirchhoff** [comment]
please move the last task in the acceptance criteria, since it is an acceptance criteria.
